---
title: "Client Report - [Baseball Over the Years]"
subtitle: "Course DS 250"
author: "[Darren Chambers]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
import sqlite3
```

```{python}
sqlite_file = 'lahmansbaseballdb.sqlite'
con = sqlite3.connect(sqlite_file)

q = 'SELECT * FROM allstarfull LIMIT 5'
results = pd.read_sql_query(q,con)

# results
```


## Elevator pitch

_When considering baseball players it is important to look at their average hits. Within this average we see that the number of total hits and At bats is very important for choosing players for a team. Somebody with a couple thousand at bats but a lower % is better than someone with 10 at bats and 60% hit rate. _

## QUESTION|TASK 1

__Write an SQL query to create a new dataframe about baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, and the yearID/teamID associated with each salary. Order the table by salary (highest to lowest) and print out the table in your report.__


_I made sure to only display unique values in this table, meaning I used distinct to ensure there were no repeating values and it is ordered by salary. We can see that there are only 2 players who had attented byui. One thing to note is that as these two players gained experience their salaries increased. Lindsman though lost some pay in 2013 comapared to his previous 2 years._
```{python}

q = '''SELECT DISTINCT cp.playerID, cp.schoolID, s.salary, s.yearID, s.teamID
FROM collegeplaying cp
JOIN salaries s ON cp.playerID = s.playerID
WHERE cp.schoolID = 'idbyuid'
ORDER BY s.salary DESC'''

result = pd.read_sql_query(q, con)

print(result)
```

```{python}
# sqlite_file = 'lahmansbaseballdb.sqlite'
# con = sqlite3.connect(sqlite_file)

# q = 'SELECT * FROM allstarfull LIMIT 5'
# results = pd.read_sql_query(q,con)

# results
```

```{python}
# Use pandas to read the SQL query into a DataFrame
# df = pd.read_sql_query(q, con)

# # Close the SQLite database connection
# #con.close()

# # Print the DataFrame
# print(df)
```



## QUESTION|TASK 2

__This three-part question requires you to calculate batting average (number of hits divided by the number of at-bats)__

__Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

__Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.__

__Now calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats, and print the top 5 results.__

_The top hitters in this situation have an average hit rate of 100%. If you look in the H (hits) row you will see they have only hit once, as well as been at bat once. 
```{python}
q = '''
SELECT playerID, yearID, H, AB, (H * 100) / AB * 1.0 AS "Average Hits %"
FROM batting
WHERE AB >= 1 
GROUP BY playerID
ORDER BY H * 100/AB *1.0 DESC, playerID 
LIMIT 5'''

result = pd.read_sql_query(q, con)

print(result)
```

_When you take the At Bats and increase it to at least 10 times you see that the highest stat is 64% instead of 100% like the previous chart. These percentiles are much more useful as they have at least some data behind them. These top five batters all were at bat 11-16 times._

```{python}
q = '''
SELECT playerID, yearID, H, AB, (H * 100) / AB * 1.0 AS "Average Hits %"
FROM batting
WHERE AB >= 10 
GROUP BY playerID
ORDER BY H * 100/AB *1.0 DESC 
LIMIT 5'''

result = pd.read_sql_query(q, con)

print(result)
```

_In this last set of data you see the Average Hits go down even further from before. However, this is the most useful of the charts. All of these batters had well over 100 bats, meaning that they have many actual data points to use for their average hits. If you were to look at players you were interested in hiring for a team, the amount of Hits and at bats influencing the Average hits would be important to note. Concistency over long periods / many data points and average hits at 49% would be much more indicative of good hitters than someone who has been at bat 14 times and has a 64% average hit rate. 
```{python}

q = """ 
SELECT playerID, sum(H), sum(AB), (SUM(H) * 100) / sum(AB) * 1.0 AS "Average hits %"
FROM batting 
GROUP BY playerID 
HAVING SUM(AB) >= 100
ORDER BY  sum(H) * 100/ sum(AB) *1.0 DESC
LIMIT 5
"""
result = pd.read_sql_query(q, con)

print(result) 
```


## QUESTION|TASK 3

__Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Write an SQL query to get the data you need, then make a graph using Plotly Express to visualize the comparison. What do you learn?__

_Philidelfia Phillies vs New York Yankies for 10 years. That is 2006 - 2016. I chose these two popular teams to see how they average over time. This chart shows their average Home Runs with the New York Yankies averaging higher by 2%._


```{python}

q= '''SELECT DISTINCT teamID, 
       SUM(HR) AS Total_Home_Runs, 
       SUM(H) AS Total_Hits, 
       SUM(AB) AS Total_At_Bats, 
       (SUM(HR) * 100.0) / SUM(H) AS "Average Home Runs %"
FROM teams
WHERE teamID IN ('PHI', 'NYA') AND yearID >= 2006
GROUP BY teamID
ORDER BY "Average_Home_Runs_Percentage" DESC'''

result = pd.read_sql_query(q, con)

print(result)

```

_This chart is looking at the total pay to players over ten years and the average pay of players over the same period of time. New York Yankes paid 2.26 billion dollars over 10 years to their players, this is 870million dollars more than the Phillidelphia Phillies_

```{python}

q = '''SELECT teamID, 
              ROUND(SUM(salary), 3) AS Total_Player_Pay, 
              ROUND((SUM(salary) / COUNT(playerID)), 3) AS Average_Player_Salary
       FROM salaries
       WHERE teamID IN ('PHI', 'NYA') AND yearID >= 2006
       GROUP BY teamID
       ORDER BY Average_Player_Salary DESC'''


result = pd.read_sql_query(q, con)

print(result)
```

_These First Chart shown is the top 10 teams with highest total player pay over ten years and their average player salaries. The Second Chart is those same teams Average % Home Runs. When comparing these charts we see that the New York Yankies pay the most as well as have a 2% higher Home Run Average. 
However, the other top 8 teams are within 1.3% of each other and pay does not seem to affect their results significantly. Example is that Boston (BOS) has payed about 500 million more than the Chicogo White Socks (CHA) Yet BOS is in 5th place and CHA is in 2nd for Average Home Runs. A million dollar difference in average player salary between the two and BOS is .52% below on Home Runs.   _ 

```{python}
q = '''SELECT teamID, 
              ROUND(SUM(salary), 3) AS Total_Player_Pay, 
              ROUND((SUM(salary) / COUNT(playerID)), 3) AS Average_Player_Salary
       FROM salaries
       WHERE yearID >= 2006
       GROUP BY teamID
       ORDER BY Average_Player_Salary DESC
       LIMIT 10 '''

q2 = '''SELECT DISTINCT teamID, 
       SUM(HR) AS Total_Home_Runs, 
       SUM(H) AS Total_Hits, 
       SUM(AB) AS Total_At_Bats, 
       (SUM(HR) * 100.0) / SUM(H) AS "Average Home Runs %"
FROM teams
WHERE teamID IN ('NYA','BOS','LAN','DET','PHI','LAA','SFN','CHN','CHA','NYN') AND yearID >= 2006
GROUP BY teamID
ORDER BY "Average Home Runs %" DESC'''



result = pd.read_sql_query(q, con)

print(result)

result2 = pd.read_sql_query(q2, con)

print(result2)
```
