---
title: "Client Report - [Usage of Names over time]"
subtitle: "Course DS 250"
author: "[Darren Chambers]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_With this data we can see the change in popularity of names over time. An example of this is with the names Mary, Martha, Paul and Peter, they lost popularity by an average of 31.25% per year from 1957 to the year 2000.  _

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")



```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_In the year 1947 there were only 5 children named Darren. The name started to gain popularity in 1958 with 385 kids given the name and peaking at 5931 children given this name in 1965. I was born in the year 1996 where the popularity of the name Darren had declined by 81% from 1947.        _

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
 #and "va != 0"])
# df.query("year <= 2000") 

# year with lowest babies names Darren
# pd.unique(df.query("name == 'Darren' ").year).min()
# pd.unique(df.query("name == 'Darren' ").year).max()

# Gives the size, so rows times columns so with year, how many years you have, name: how many times the specified name occurs. 
# pd.unique(df.query("name == 'Darren' ").year).size
df.query("name == 'Darren'").filter(["name", "year", "Total"]).query("year > 1990 and year < 2000")
```

_The green line indicates when I was born.  _

```{python}
#| label: Q1 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
darren_df = df[df['name'] == 'Darren']
chart = px.bar(darren_df.head(200),
    x="year", 
    y="Total",
    title = "Usage of the name Darren",
    labels = {"year":"Year"}

)
highlight_year = 1996

# Add a vertical line
chart.add_shape(
    type="line",
    x0=highlight_year,
    y0=darren_df['Total'].min(),
    x1=highlight_year,
    y1=darren_df['Total'].max(),
    line=dict(
        color="green",
        width=3,
        dash="dashdot"
    )
)
chart.show()

```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_I would guess they would be born between the years 1985 and 1996. Which would be between the ages of 27 and 38. The reason why I would choose this range of age is because the majority of people named brittany were born in these years. 241847 out of 327718 were born in these years. That is 
73.8% of people named Brittany in a 11 year period.I would not choose any date from 1968 - 1984 and 1997 and 2015 because that is only 26.2 % of people name Brittany were born in these years.  _

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here

df.query("name == 'Brittany'").filter(["name", "year",
 "Total"]).query("year > 1984 and year < 1997")


```

_This is isolating the years that hold  73.8% of people named Brittany_

```{python}
#| label: Q2 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
filtered_df = df[df['name'] == 'Brittany']
chart = px.bar(filtered_df.head(200),
    x="year", 
    y="Total",
    title = "Brittany name usage over the years"
)
chart.add_shape(
    type="line",
    x0= 1985,
    y0=14000,
    x1=1996,
    y1=14000,
    line=dict(
        color="red",
        width=3,
        dash="dashdot")
        )
chart.show()
```


```{python}
#| label: Q2 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = filtered_df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_These four names follow the same trend line in popularity over time. This may be due to cultural shifts in the popularity of christianity. Between 1947 and 1957 was the peak of usage of these names with an average usage of 201149 This drops relativly quickly over the years with an average percent decrese of 31.45% over 43 years.


```{python}
#| label: Q3 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
desired_names = ["Mary", "Martha", "Peter", "Paul"]
#List of names I want to see in chart
#isin is boolean check. Is the four names in the column?
# filter_df = df.name.isin(desired_names)
# filter_df = df[df["name"].isin(desired_names)]
filter_df = df[df.name.isin(desired_names)].query("year > 1919 and year < 2001")
#takes filter and query filter_df variable and applies to the chart. 
chart = px.bar(filter_df,
    x="year", 
    y="Total",
    color = "name",
    title = "Comparison of Martha, Mary, Peter and Paul over the years",
    labels = {"year": "Year"}
)
chart.show()
```


```{python}
#| label: Q3 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here

# Taking instances of each record and adding them together.
mydat = (df
    [df.name.isin(desired_names)]
    .query('year > 1947 and year < 1957')
    .groupby('name')
    .agg(total = ('Total', 'sum'))
    .reset_index()
)

mydat.head(50)



# mydat = filter_df.head(1000)\
#     .groupby('year')\
#     .sum()\
#     .reset_index()\
#     .tail(10)\
#     .filter(["year", "AK","AR"])

# display(mydat)

```

## Question|Task 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_I chose the name Allison from Raiders of the Lost Ark. This movie released in 1981, The name began to gain popularity and over 4 years increase by 43.36%. The movie was the most popular movie of 1981 and so would potentially affect the usage of names over the next couple of years.  
```{python}

movie_df = df[df['name'] == 'Allison']
chart = px.bar(movie_df.head(200),
    x="year", 
    y="Total",
    title = "Allison name usage over the years",
    labels = {"year": "Year"}
)
chart.add_shape(
    type="line",
    x0= 1981,
    y0=4990,
    x1=1984,
    y1=7000,
    line=dict(
        color="red",
        width=3,
        dash="dashdot")
        )
chart.show()
```